version: "3.8"

services:
  # Banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: onfly-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onfly
      MYSQL_USER: onfly
      MYSQL_PASSWORD: onfly
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - onfly-network

  # Backend Laravel
  backend:
    build:
      context: ./onfly-api
      dockerfile: Dockerfile
    container_name: onfly-backend
    env_file:
      - ./onfly-api/.env.docker
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./onfly-api:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - onfly-network

  # Frontend Vue.js
  frontend:
    build:
      context: ./onfly-front
      dockerfile: Dockerfile
    container_name: onfly-frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./onfly-front:/app
      - /app/node_modules
    networks:
      - onfly-network

volumes:
  db_data:

networks:
  onfly-network:
    driver: bridge
